### ISSUE TITLE
Duplicated avatar when entering room

### ISSUE THREAD

**Issue by matotubol** [80O/PlusEMU#44]
Sometimes when entering a room the avatar will get duplicated.
Im not sure how to reproduce this bug since it only happens sometimes.
![duplicated](https://user-images.githubusercontent.com/31701668/165166093-ad8f8260-bdd7-4f97-bcca-7909bc5f1502.png)

**Comment by leolkr** [comment]
It happens when you create a new room.

**Comment by 80O** [comment]
I noticed too that the navigator says 3 people in the room when the room was newly created. Possibly related?

**Comment by Shetlands** [comment]
> 

it's always the same number yes, not 1 less, not 1 more

**Comment by leolkr** [comment]
![Inkedcreateroom_LI](https://user-images.githubusercontent.com/83711434/165198137-54a56537-9bb9-4414-a550-8e71775a3c18.jpg)
Is it three, because the packets get handled 3 times?
If you use :chooser you can see there are 3 users in the room, not a duplicate.

**Comment by Shetlands** [comment]
yes it's very strange, when you send a message it sends it 3 times. On the other hand, if you change your outfit, or do an emote, etc., the other two do nothing.

**Comment by DamienJolly** [comment]
From what I've gathered there's a glaring issue in `public bool AddAvatarToRoom(GameClient session)`, there are no checks to see if the user is already in the room what so ever. The fix posted by Mathys doesn't fix the issue at all. The RoomEntity needs to be stored with the users currentroom and a if statement needs to be added in that method stop multiple users from being added.

I'm actually kinda curious if you flooded the client with the packet `GetRoomEntryDataEvent` while in a room if it would flood the room with avatars.

Also this doesn't fix the issue of why the the room loading packets get sent 3 times. But this fixes the quite a jarring exploit that gets exposed because of the duplicate packets.

**Comment by leolkr** [comment]
I want to use G-Earth for such things but I cant get it to work locally

**Comment by IDjinn** [comment]
is this still happens?

**Comment by IDjinn** [comment]
`room.GetRoomUserManager().AddAvatarToRoom(session)` from `GetRoomEntryDataEvent.cs` is called twice  (may 3 times) when you're creating new room.

**Comment by Diddyy** [comment]
It has happened to me today, can't remember what I did to cause it but it did >.<

**Comment by Shetlands** [comment]
> is this still happens?

yes, I had spent several hours trying to find where it could come from, I had not found

> It has happened to me today, can't remember what I did to cause it but it did >.<

as said above by @leolkr it happens when you create a room

**Comment by IDjinn** [comment]
hasn't figure out. but it is adding new avatar couple times. Should be some modification in room user manager or gamemap files

**Comment by IDjinn** [comment]
After some tries, i guess i found where is wrong. I saw PacketManager as async handling packets, i turned it to sync and everything is working like should be... Still need why same packet is handled 3 times but avatar is not duplicated anymore
